"""Markdown security report generator for Cloud Attack Path Visualiser.

Generates comprehensive, formatted markdown reports from AnalysisResult instances,
including summary metrics, detected findings, detailed attack path chains,
recommended remediations, and optional AI Analyst explanations.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from .models import AnalysisResult, AttackPath, Finding


def _format_severity_badge(severity: str) -> str:
    """Format markdown text with severity emoji badges."""
    s = severity.upper()
    if s == "CRITICAL":
        return "🔴 **CRITICAL**"
    elif s == "HIGH":
        return "🟠 **HIGH**"
    elif s == "MEDIUM":
        return "🟡 **MEDIUM**"
    elif s == "LOW":
        return "🟢 **LOW**"
    return f"ℹ️ **{s}**"


def build_markdown_report(
    result: AnalysisResult,
    explanations: dict[str, Any] | None = None,
) -> str:
    """Build a comprehensive markdown security analysis report.

    Args:
        result: AnalysisResult containing scenario config, findings, and paths.
        explanations: Optional dictionary mapping path keys or indices to
            explanation dictionaries generated by ai_explainer.

    Returns:
        Formatted markdown report string.
    """
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    scenario_name = result.config.scenario_name or "Cloud Infrastructure"

    lines: list[str] = [
        "# 🛡️ Cloud Security & Attack Path Analysis Report",
        "",
        f"**Generated:** {now_str}  ",
        f"**Scenario:** `{scenario_name}`  ",
        f"**Framework:** Defensive Cloud Attack Path Discovery Engine  ",
        "",
        "---",
        "",
        "## 1. Executive Summary & Metrics",
        "",
        "| Metric | Count | Description |",
        "| :--- | :---: | :--- |",
        f"| **Total Resources** | {len(result.config.resources)} | Cloud infrastructure resources scanned |",
        f"| **Security Findings** | {len(result.findings)} | Misconfigurations detected by deterministic rules |",
        f"| **Attack Paths** | {len(result.paths)} | Simple paths discovered from entry points to sensitive targets |",
        f"| **Critical Risk Paths** | {sum(1 for p in result.paths if p.severity == 'CRITICAL')} | Paths with risk score ≥ 80 |",
        f"| **High Risk Paths** | {sum(1 for p in result.paths if p.severity == 'HIGH')} | Paths with risk score 60–79 |",
        f"| **Medium Risk Paths** | {sum(1 for p in result.paths if p.severity == 'MEDIUM')} | Paths with risk score 35–59 |",
        "",
    ]

    # ── 2. Security Findings Table ──────────────────────────────────────
    lines.append("## 2. Detected Security Findings")
    lines.append("")

    if not result.findings:
        lines.append("✅ **No security misconfigurations detected** in this scenario.")
        lines.append("")
    else:
        lines.append(
            "| Severity | Finding ID | Rule | Affected Resource | Description | Recommendation |"
        )
        lines.append(
            "| :--- | :--- | :--- | :--- | :--- | :--- |"
        )
        for f in result.findings:
            sev_badge = _format_severity_badge(f.severity)
            clean_desc = f.description.replace("|", "\\|").replace("\n", " ")
            clean_rec = f.recommendation.replace("|", "\\|").replace("\n", " ")
            lines.append(
                f"| {sev_badge} | `{f.id}` | `{f.rule}` | `{f.resource_id}` | {clean_desc} | {clean_rec} |"
            )
        lines.append("")

    # ── 3. Discovered Attack Paths ──────────────────────────────────────
    lines.append("## 3. Discovered Attack Paths")
    lines.append("")

    if not result.paths:
        lines.append("🛡️ **No attack paths discovered.**")
        lines.append("")
        lines.append(
            "All sensitive destination assets (e.g. database stores, secrets, and private buckets) "
            "are properly isolated from public entry points."
        )
        lines.append("")
    else:
        for idx, p in enumerate(result.paths, start=1):
            sev_badge = _format_severity_badge(p.severity)
            source = p.nodes[0]
            target = p.nodes[-1]
            hop_count = max(0, len(p.nodes) - 1)

            lines.append(f"### Path {idx}: `{source}` ➔ `{target}`")
            lines.append("")
            lines.append(
                f"- **Risk Score:** `{p.score}/100`  "
                f"- **Severity:** {sev_badge}  "
                f"- **Hops:** `{hop_count}`  "
            )
            lines.append("")

            # Visual Chain
            chain_parts = []
            for i, nid in enumerate(p.nodes):
                chain_parts.append(f"`{nid}`")
                if i < len(p.nodes) - 1:
                    edge_type = p.edges[i] if i < len(p.edges) else "connects_to"
                    chain_parts.append(f"━━[{edge_type}]━━▶")
            lines.append(f"**Attack Chain:**  \n{' '.join(chain_parts)}")
            lines.append("")

            # Additive Model Reasons
            if p.reasons:
                lines.append("**Scoring Factors:**")
                for r in p.reasons:
                    lines.append(f"- {r}")
                lines.append("")

            # Recommended Fixes
            lines.append("**Recommended Fixes:**")
            path_nodes_set = set(p.nodes)
            path_findings = [f for f in result.findings if f.resource_id in path_nodes_set]
            fixes_added = set()

            for f in path_findings:
                if f.recommendation and f.recommendation not in fixes_added:
                    lines.append(f"- **[{f.resource_id}]**: {f.recommendation}")
                    fixes_added.add(f.recommendation)

            if any("0.0.0.0/0" in r or "security group" in r.lower() for r in p.reasons):
                fix_sg = "Restrict security group ingress: remove 0.0.0.0/0 on sensitive ports (22, 3389, 3306, 5432)."
                if fix_sg not in fixes_added:
                    lines.append(f"- {fix_sg}")
                    fixes_added.add(fix_sg)

            if any("wildcard" in r.lower() or "admin" in r.lower() for r in p.reasons):
                fix_iam = "Enforce least-privilege IAM policies: eliminate wildcard actions ('*') and scope role policies to explicit ARNs."
                if fix_iam not in fixes_added:
                    lines.append(f"- {fix_iam}")
                    fixes_added.add(fix_iam)

            if not fixes_added:
                lines.append("- Enforce strict network segmentation and isolate intermediate compute resources.")
            lines.append("")

            # ── 4. AI Explanation for this Path (if available) ──────────
            expl = None
            if explanations:
                # Try path tuple key, int index, or string index
                expl = (
                    explanations.get(tuple(p.nodes))
                    or explanations.get(f"{scenario_name}_{tuple(p.nodes)}")
                    or explanations.get(idx - 1)
                    or explanations.get(str(idx - 1))
                    or explanations.get(f"path_{idx}")
                )

            if expl and isinstance(expl, dict):
                source_lbl = "OpenAI (gpt-4o-mini)" if expl.get("source") == "openai" else "Deterministic Fallback"
                lines.append(f"#### 🤖 AI Security Analyst Assessment ({source_lbl})")
                lines.append("")
                if expl.get("executive_summary"):
                    lines.append(f"> **Executive Summary:** {expl['executive_summary']}")
                    lines.append("")
                if expl.get("summary"):
                    lines.append(f"**Technical Summary:**  \n{expl['summary']}")
                    lines.append("")
                if expl.get("why_it_exists"):
                    lines.append(f"**Root Cause Analysis:**  \n{expl['why_it_exists']}")
                    lines.append("")
                if expl.get("impact"):
                    lines.append(f"**Potential Impact:**  \n{expl['impact']}")
                    lines.append("")
                if expl.get("remediation") and isinstance(expl["remediation"], list):
                    lines.append("**AI Recommended Actions:**")
                    for s in expl["remediation"]:
                        lines.append(f"1. {s}")
                    lines.append("")

            lines.append("---")
            lines.append("")

    # Footer
    lines.append(
        "*\n*Defensive Security Notice: This automated analysis report is generated for defensive evaluation "
        "and architectural hardening of simulated cloud environments.*"
    )

    return "\n".join(lines)
